function Data = updateGuildInfo(Data)
gtypes = {Data.Guilds.type};

iProducerGuilds = find(strcmpi(gtypes,'Producer'));
iConsumerGuilds = find(strcmpi(gtypes,'Consumer'));
iFoodGuilds = find(any(Data.communityMatrix,1));
iFeederGuilds = find(any(Data.communityMatrix,2))';
nGuilds = length(Data.Guilds);
nFoodGuilds = length(iFoodGuilds);     %cuantos gremios son recurso
nFeederGuilds = length(iFeederGuilds); %cuantos gremios son consumidores
iProducerGuildsInFood = iProducerGuilds(ismember(iProducerGuilds,iFoodGuilds)); %nuevo, con esto la identidad
iConsumerGuildsInFood = iConsumerGuilds(ismember(iConsumerGuilds,iFoodGuilds)); %nuevo y asigna correctamente
iProducerGuildsInFood_position_vector = find(ismember(iFoodGuilds,iProducerGuilds)); %posiicon que los productores tienen en el grupo FoodGuilds y en LossVec
iConsumerGuildsInFood_position_vector = find(ismember(iFoodGuilds,iConsumerGuilds)); %posiicon que los consumidores tienen en el grupo FoodGuilds y en LossVec

%iProducerGuildsInFood = find(ismember(iFoodGuilds,iProducerGuilds)); % este
%estaba en el antiguo codigo pero no funciona correctamente porque la
%identidad de las especies no las asugna bien. En los pp esta bien porque
%todos los pp son comidos, pero si no fuera el caso, los asignaria en fomra
%incorrecta.
%iConsumerGuildsInFood = find(ismember(iFoodGuilds,iConsumerGuilds));% este
%estaba en el antiguo codigo pero no funciona correctamente porque la
%identidad de las especies no las asugna bien

%%%FROM HERE, SEE THE ORIGINAL BELOW 
Data.GuildInfo = struct( ...
    'iProducerGuilds', iProducerGuilds, ...
    'iConsumerGuilds', iConsumerGuilds, ...
    'iFoodGuilds', iFoodGuilds, ...
    'iFeederGuilds', iFeederGuilds, ...
    'nGuilds', nGuilds, ...
    'nFoodGuilds', nFoodGuilds, ...
    'nFeederGuilds', nFeederGuilds, ...
    'iProducerGuildsInFood', iProducerGuildsInFood, ...
    'iConsumerGuildsInFood', iConsumerGuildsInFood, ...
    'iProducerGuildsInFood_position_vector', iProducerGuildsInFood_position_vector, ...
    'iConsumerGuildsInFood_position_vector', iConsumerGuildsInFood_position_vector);
%%%THE ORIGINAL%%%
%Data.GuildInfo = struct( ...
    %'iDetritusGuilds', iDetritusGuilds, ...
    %'iDOC1', iDOC1, ...
    %'iDOC2', iDOC2, ...
    %'iProducerGuilds', iProducerGuilds, ...
    %'iConsumerGuilds', iConsumerGuilds, ...
    %'iFishGuilds', iFishGuilds, ...
    %'iFoodGuilds', iFoodGuilds, ...
    %'iFeederGuilds', iFeederGuilds, ...
    %'iConsumerAndFishGuilds', iConsumerAndFishGuilds, ...
    %'iLarvaeFishGuilds', iLarvaeFishGuilds, ...
    %'iJuvenileFishGuilds', iJuvenileFishGuilds, ...
    %'iAdultFishGuilds', iAdultFishGuilds, ...
    %'nGuilds', nGuilds, ...
    %'nFishSpecies', nFishSpecies, ...
    %'nFishGuilds', nFishGuilds, ...
    %'nFoodGuilds', nFoodGuilds, ...
    %'nFeederGuilds', nFeederGuilds, ...
    %'nAdultFishGuilds', nAdultFishGuilds, ...
    %'nLarvaeFishGuilds', nLarvaeFishGuilds, ...
    %'nJuvenileFishGuilds', nJuvenileFishGuilds, ...
    %'iAdultFishGuildsInFish', iAdultFishGuildsInFish, ...
    %'iDOC2InFoodGuilds', iDOC2InFoodGuilds, ...
    %'iProducerGuildsInFood', iProducerGuildsInFood, ...
    %'iFishGuildsInConsumers', iFishGuildsInConsumers, ...
    %'iFishGuildsInFeeders', iFishGuildsInFeeders, ...
    %'iFishGuildsInFood', iFishGuildsInFood, ...
    %'iFishFoodInFishGuilds', iFishFoodInFishGuilds, ...
    %'iNonFishGuildsInConsumers', iNonFishGuildsInConsumers, ...
    %'iNonFishGuildsInFeeders', iNonFishGuildsInFeeders, ...
    %'iConsumerGuildsInFood', iConsumerGuildsInFood, ...
    %'FishAges', FishAges);

